### ISSUE TITLE
Do not require ext-debug

### ISSUE THREAD

**Issue by garak** [Lewiscowles1986/ulid#15]
Requiring ext-debug in dev is too strict.
Not every dev environment is using xdebug (mine, for example, is not), to be able to save time during tests.
Moreover, phpunit configuration proposed in this library is not using coverage, so xdebug is not needed.

**Comment by Lewiscowles1986** [comment]
Please read readme.md coverage is absolutely used in my own internal CI so it's part of the lib.

**Comment by garak** [comment]
Well, it's used in *your own* internal CI, that is a specific environment. Setting this a requirement means that it's required in *every* environment, that is simply too strict. For example, the current travis is failing just because this.

**Comment by Lewiscowles1986** [comment]
The current travis is not failing because I took the time to add extra to the `travis.yml`.

Anyone developing using this library should be using the commands shown in README.md so they can be sure they are not degrading code coverage. I do absolutely appreciate the time and effort you're putting into making this nice and I've accepted those changes. This change is unacceptable. If people want to edit their own composer.json and exclude it from commit they are free to do so, but I feel they should use the commands I suggest locally to get coverage when they run tests.

**Comment by garak** [comment]
But, again, the phpunit configuration in this library is not using coverage. And, well, it's good to suggest using coverage, but *forcing* to coverage is different (and it's something I've never seen in any other PHP library or project).
Also, the "require-dev" section of composer is not limited to test environment, it's including development environment, where forcing xdebug doesn't make sense.

**Comment by Lewiscowles1986** [comment]
devs should be testing... dev and testing should not be separate things, I'm sorry but I don't agree on this change

**Comment by garak** [comment]
dev and testing **could** be the same, but that's a specific case. In general, they're different environment, otherwise there's should be no reason to call them with different names. Of course, they **share** some features, but you can't say they're the same.
Again, this is not my personal opinion, it's just the way everyone else in the PHP world is going on.
